### ISSUE TITLE
using catvae without a phylogeny

### ISSUE THREAD

**Issue by cameronmartino** [flatironinstitute/catvae#75]
Hi @mortonjt,

Is it okay to train a catvae model without a phylogeny? If so, how should I extract the embeddings index IDs from the model output? I see all the utils rely on the phylogeny for the index order. 

Thanks!

**Comment by mortonjt** [comment]
Hi! Yes you don’t need to specify a phylogeny - if none is specified , a
random phylogeny will be generated.

https://github.com/flatironinstitute/catvae/blob/master/catvae/models/linear_vae.py#L16

It wont really matter which tree you use for estimation - but it can help
with interpretation.

**Comment by cameronmartino** [comment]
@mortonjt For the order of the index IDs without the tree in the embedding is it just the order of the IDs in the biom tables? or ALR first or last IDs? so `bt.ids('observation')[1:]` or  `bt.ids('observation')[:-1]`?

Thanks!!

**Comment by cameronmartino** [comment]
Maybe to be more explicit. When I do:

```python
W = model.vae.decoder.weight.detach().cpu().numpy()
dist_W = squareform(pdist(W))
dist_Wdf = pd.DataFrame(dist_W)
```

How would I grab the correct IDs order for `dist_Wdf` and am I calculating `dist_Wdf` correctly?

Thanks!!

**Comment by mortonjt** [comment]
See the Readme on extracting embeddings. I have a helper function to do
this

https://github.com/flatironinstitute/catvae/blob/master/catvae/util.py#L70

**Comment by cameronmartino** [comment]
Right, but those require a basis/phylogeny `tree` as input in order to get the correct order of the IDs. How should I do it without one?

**Comment by mortonjt** [comment]
Got it. Ok, don’t use the defaults. Id use the random_linkage function
(used in that get_basis method) to get you a random phylogeny - which you
can use the helper methods listed previously

**Comment by cameronmartino** [comment]
That worked. Thanks!!

**Comment by cameronmartino** [comment]
FYI - it only really works if you make the tree ahead of time and plug it in (otherwise it won't match).  Might be good to expose the tree in the model class (i.e. self.tree) so one could pull it out after if needed.
